(base) root@EC03-E01-AICO3:/home/CORP/re_nikitav# docker logs 3214515f1998

==========
== CUDA ==
==========

CUDA Version 13.0.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

INFO:     Started server process [1]
INFO:     Waiting for application startup.
2026-09-17 14:30:51,980 | INFO | GPU: NVIDIA A10G
2026-09-17 14:30:51,980 | INFO | Torch CUDA: 12.6
2026-09-17 14:30:52,121 | INFO | HTTP Request: GET https://huggingface.co/api/agent-harnesses "HTTP/1.1 200 OK"
2026-09-17 14:30:52,156 | INFO | HTTP Request: HEAD https://huggingface.co/ResembleAI/chatterbox-flash/resolve/main/ve.safetensors "HTTP/1.1 302 Found"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-17 14:30:52,157 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-17 14:30:52,194 | INFO | HTTP Request: GET https://huggingface.co/api/models/ResembleAI/chatterbox-flash/xet-read-token/4385507288b8197e6dab8b4e6b1603328d549d9d "HTTP/1.1 200 OK"
2026-09-17 14:30:53,415 | INFO | HTTP Request: HEAD https://huggingface.co/ResembleAI/chatterbox-flash/resolve/main/t3_flash.safetensors "HTTP/1.1 302 Found"
2026-09-17 14:32:29,590 | INFO | HTTP Request: HEAD https://huggingface.co/ResembleAI/chatterbox-flash/resolve/main/s3gen.safetensors "HTTP/1.1 302 Found"
2026-09-17 14:32:59,676 | INFO | HTTP Request: HEAD https://huggingface.co/ResembleAI/chatterbox-flash/resolve/main/tokenizer.json "HTTP/1.1 307 Temporary Redirect"
2026-09-17 14:32:59,694 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/ResembleAI/chatterbox-flash/4385507288b8197e6dab8b4e6b1603328d549d9d/tokenizer.json?%2FResembleAI%2Fchatterbox-flash%2Fresolve%2Fmain%2Ftokenizer.json=&etag=%22abd07c710243ba89bf1b21780e7c37ddde92334e%22 "HTTP/1.1 200 OK"
2026-09-17 14:32:59,724 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/ResembleAI/chatterbox-flash/4385507288b8197e6dab8b4e6b1603328d549d9d/tokenizer.json?%2FResembleAI%2Fchatterbox-flash%2Fresolve%2Fmain%2Ftokenizer.json=&etag=%22abd07c710243ba89bf1b21780e7c37ddde92334e%22 "HTTP/1.1 200 OK"
/opt/venv/lib/python3.12/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
2026-09-17 14:33:09,051 | INFO | input frame rate=25
2026-09-17 14:33:09,852 | INFO | Model loaded in 137871.56 ms | sample_rate=24000
2026-09-17 14:33:26,810 | INFO | Reference conditioning prepared in 16958.48 ms
2026-09-17 14:33:26,811 | INFO | Warming model...
/usr/lib/python3.12/contextlib.py:105: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
/opt/venv/lib/python3.12/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:192: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
We recommend installing via `pip install torch-c-dlpack-ext`
  warnings.warn(
2026-09-17 14:33:36,224 | INFO | FlashInferEngine: max_seq=406 layers=30 heads=16/16 dim=64 batch=2 page_size=16 pages/sample=26 total_pages=52 rope_inplace=False dtype=torch.bfloat16
2026-09-17 14:33:36,269 | ERROR | Warmup failed; server remains available.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/flashinfer/jit/cpp_ext.py", line 370, in run_ninja
    subprocess.run(
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-C', '/root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True', '-f', '/root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/build.ninja']' returned non-zero exit status 127.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/server.py", line 120, in startup
    _ = generate_full("Hello.")
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server.py", line 76, in generate_full
    return tts.generate(
           ^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/chatterbox-flash/chatterbox_flash/tts.py", line 269, in generate
    speech_tokens = self.t3.generate(
                    ^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/chatterbox-flash/chatterbox_flash/model.py", line 769, in generate
    shift_ctx = engine.prefix_forward(pfx_for_engine)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/chatterbox-flash/chatterbox_flash/engines/flashinfer.py", line 484, in prefix_forward
    return self._prefix_forward_batched(prefix_emb_or_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/chatterbox-flash/chatterbox_flash/engines/flashinfer.py", line 754, in _prefix_forward_batched
    self._fi_ragged_wrapper.plan(
  File "/opt/venv/lib/python3.12/site-packages/flashinfer/prefill.py", line 3883, in plan
    self._cached_module = get_batch_prefill_module(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/flashinfer/prefill.py", line 468, in get_batch_prefill_module
    module = gen_batch_prefill_module(backend, *args).build_and_load()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/flashinfer/jit/core.py", line 320, in build_and_load
    self.build()
  File "/opt/venv/lib/python3.12/site-packages/flashinfer/jit/core.py", line 427, in build
    run_ninja(self.build_dir, self.ninja_path, verbose)
  File "/opt/venv/lib/python3.12/site-packages/flashinfer/jit/cpp_ext.py", line 382, in run_ninja
    raise RuntimeError(msg) from e
RuntimeError: Ninja build failed. Ninja output:
ninja: Entering directory `/root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True'
[1/11]  /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_0.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_paged_kernel_mask_0.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_0.cuda.o
FAILED: [code=127] /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_0.cuda.o
 /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_0.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_paged_kernel_mask_0.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_0.cuda.o
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
[2/11]  /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_0.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_ragged_kernel_mask_0.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_0.cuda.o
FAILED: [code=127] /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_0.cuda.o
 /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_0.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_ragged_kernel_mask_0.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_0.cuda.o
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
[3/11]  /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_1.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_paged_kernel_mask_1.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_1.cuda.o
FAILED: [code=127] /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_1.cuda.o
 /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_1.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_paged_kernel_mask_1.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_1.cuda.o
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
[4/11]  /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_1.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_ragged_kernel_mask_1.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_1.cuda.o
FAILED: [code=127] /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_1.cuda.o
 /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_1.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_ragged_kernel_mask_1.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_1.cuda.o
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
[5/11]  /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_2.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_paged_kernel_mask_2.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_2.cuda.o
FAILED: [code=127] /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_2.cuda.o
 /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_2.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_paged_kernel_mask_2.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_2.cuda.o
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
[6/11]  /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_2.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_ragged_kernel_mask_2.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_2.cuda.o
FAILED: [code=127] /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_2.cuda.o
 /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_2.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_ragged_kernel_mask_2.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_2.cuda.o
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
[7/11]  /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_3.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_paged_kernel_mask_3.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_3.cuda.o
FAILED: [code=127] /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_3.cuda.o
 /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_3.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_paged_kernel_mask_3.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_paged_kernel_mask_3.cuda.o
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
[8/11]  /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill.cuda.o
FAILED: [code=127] /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill.cuda.o
 /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill.cuda.o
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
[9/11]  /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_3.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_ragged_kernel_mask_3.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_3.cuda.o
FAILED: [code=127] /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_3.cuda.o
 /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_3.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_ragged_kernel_mask_3.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_ragged_kernel_mask_3.cuda.o
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
[10/11]  /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_jit_binding.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_jit_binding.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_jit_binding.cuda.o
FAILED: [code=127] /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_jit_binding.cuda.o
 /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile -MF /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_jit_binding.cuda.o.d -DPy_LIMITED_API=0x03090000 -D_GLIBCXX_USE_CXX11_ABI=1 -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/cub -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/libcudacxx/include -I/opt/venv/lib/python3.12/site-packages/flashinfer/data/cccl/thrust -isystem /usr/include/python3.12 -isystem /usr/local/cuda/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/tvm_ffi/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/csrc -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/cutlass/tools/util/include -isystem /opt/venv/lib/python3.12/site-packages/flashinfer/data/spdlog/include --compiler-options=-fPIC --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 -DFLASHINFER_ENABLE_FP8_E8M0 -DFLASHINFER_ENABLE_FP4_E2M1 -std=c++17 --threads=1 -use_fast_math -Xfatbin=-compress-all --compress-mode=size -DFLASHINFER_ENABLE_F16 -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8_E4M3 -DFLASHINFER_ENABLE_FP8_E5M2 -DNDEBUG -O3 -c /root/.cache/flashinfer/0.6.18.post1/86/generated/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_jit_binding.cu -o /root/.cache/flashinfer/0.6.18.post1/86/cached_ops/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True/batch_prefill_with_kv_cache_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_qk_64_head_dim_vo_64_posenc_0_use_swa_False_use_logits_cap_False_f16qk_True_batch_prefill_jit_binding.cuda.o
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
ninja: build stopped: subcommand failed.